# tick accounts to ignore
ignore: 
  - tick@globalpersonals.co.uk
  - bfrost@globalpersonals.co.uk
  - rwilliams@globalpersonals.co.uk
  - bhaverly@globalpersonals.co.uk
  - kjakeman@globalpersonals.co.uk
  - jchinn@globalpersonals.co.uk
  - mdainton@globalpersonals.co.uk
  - bhitchens@globalpersonals.co.uk
  - bsmith@globalpersonals.co.uk
  - dontwritetojames@gmail.com
  - mhamilton@globalpersonals.co.uk
  - ttait@globalpersonals.co.uk
